apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: html
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80